### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pertoft** [ThomasBuchinger/automate-gitflow#54]
Fresh installed ivanchuch-2 appliance

[root@manageiq01 ~]# bundle gem miq_flow-1.0.0.pre.rc1.gem
Creating gem 'miq_flow-1.0.0.pre.rc1.gem'...
MIT License enabled in config
Code of conduct enabled in config
  file_clash  miq_flow-1.0.0.pre.rc1.gem/Gemfile
  file_clash  miq_flow-1.0.0.pre.rc1.gem/lib/miq_flow/1.0.0.pre.rc1.gem.rb
  file_clash  miq_flow-1.0.0.pre.rc1.gem/lib/miq_flow/1.0.0.pre.rc1.gem/version.rb
  file_clash  miq_flow-1.0.0.pre.rc1.gem/miq_flow-1.0.0.pre.rc1.gem.gemspec
  file_clash  miq_flow-1.0.0.pre.rc1.gem/Rakefile
  file_clash  miq_flow-1.0.0.pre.rc1.gem/README.md
  file_clash  miq_flow-1.0.0.pre.rc1.gem/bin/console
  file_clash  miq_flow-1.0.0.pre.rc1.gem/bin/setup
  file_clash  miq_flow-1.0.0.pre.rc1.gem/.gitignore
  file_clash  miq_flow-1.0.0.pre.rc1.gem/LICENSE.txt
  file_clash  miq_flow-1.0.0.pre.rc1.gem/CODE_OF_CONDUCT.md
There was an error accessing `/root/miq_flow-1.0.0.pre.rc1.gem/bin/console`.
The underlying system error is Errno::ENOTDIR: Not a directory @ rb_file_s_stat - /root/miq_flow-1.0.0.pre.rc1.gem/bin/console
[root@manageiq01 ~]#

**Comment by ThomasBuchinger** [comment]
I guess you want to install the gem? I think you are looking for `gem install miq_flow-1.0.0.pre.rc1.gem`
The `bundle gem` command actually generates the files to start writig a new gem [bundle doc](https://bundler.io/v2.0/man/bundle-gem.1.html)

There is some work-in-progress documentation on the doc/docu-update branch.
https://github.com/ThomasBuchinger/miq-flow/blob/doc/docu_update/doc/user_guide.md#miq-flow-installation

**Comment by pertoft** [comment]
Hi Thomas,

Thanks for the quick reply. Apparently its me being a newbie to ruby.
The gem installation worked and miq-flow appears to work.

Thanks allot!

**Comment by ThomasBuchinger** [comment]
You are welcome
